### ISSUE TITLE
Debian testing bullseye 闪退

### ISSUE THREAD

**Issue by zhz** [bestwu/docker-wechat#18]
前些日子还挺好的，后来 apt-get upgrade 系统之后，就开始在手机确认登录之后闪退了。

系统信息：

```
        _,met$$$$$gg.           
      ,g$$$$$$$$$$$$$$$P.        OS: Debian testing bullseye
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 5.7.0-1-amd64
   ,$$P'              `$$$.      Uptime: 1d 8h 56m
  ',$$P       ,ggs.     `$$b:    Packages: 2395
  `d$$'     ,$P"'   .    $$$     Shell: zsh 5.8
   $$P      d$'     ,    $$P     Resolution: 1920x1080
   $$:      $$.   -    ,d$$'     DE: Xfce
   $$\;      Y$b._   _,d$P'      WM: Emerald
   Y$$.    `.`"Y$$$$P"'          WM Theme: 
   `$$b      "-.__               GTK Theme: TraditionalOk [GTK2]
    `Y$$                         Icon Theme: Tango
     `Y$$.                       Font: 文泉驿微米黑 10
       `$$b.                     Disk: 15T / 17T (86%)
         `Y$$b.                  CPU: Intel Core i5-3210M @ 4x 3.1GHz [56.0°C]
            `"Y$b._              GPU: Mesa DRI Intel(R) Ivybridge Mobile 
                `""""            RAM: 4862MiB / 11731MiB

```

docker 日志

```
启动 WeChat
Run Deepin-WeChat 2.6.8.65deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 

7-Zip [32] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=zh_CN.UTF-8,Utf16=on,HugeFiles=on,32 bits,4 CPUs Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (306A9),ASM,AES-NI)

Scanning the drive for archives:
1 file, 50232547 bytes (48 MiB)

Extracting archive: /opt/deepinwine/apps/Deepin-WeChat/files.7z
--
Path = /opt/deepinwine/apps/Deepin-WeChat/files.7z
Type = 7z
Physical Size = 50232547
Headers Size = 9283
Method = LZMA2:26 BCJ2
Solid = +
Blocks = 1

Everything is Ok

Folders: 109
Files: 976
Size:       156938730
Compressed: 50232547
total 0
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 c: -> ../drive_c
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com1 -> /dev/ttyS0
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com10 -> /dev/ttyS9
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com11 -> /dev/ttyS10
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com12 -> /dev/ttyS11
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com13 -> /dev/ttyS12
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com14 -> /dev/ttyS13
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com15 -> /dev/ttyS14
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com16 -> /dev/ttyS15
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com2 -> /dev/ttyS1
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com3 -> /dev/ttyS2
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com4 -> /dev/ttyS3
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com5 -> /dev/ttyS4
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com6 -> /dev/ttyS5
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com7 -> /dev/ttyS6
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com8 -> /dev/ttyS7
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com9 -> /dev/ttyS8
lrwxrwxrwx 1 wechat wechat  8 8月  22 07:51 d:: -> /dev/sdb
lrwxrwxrwx 1 wechat wechat 17 8月  22 07:51 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 wechat wechat  9 8月  22 07:51 e:: -> /dev/sdb1
lrwxrwxrwx 1 wechat wechat 12 8月  22 07:51 y: -> /home/wechat
lrwxrwxrwx 1 wechat wechat  1 8月  22 07:51 z: -> /
total 0
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 c: -> ../drive_c
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com1 -> /dev/ttyS0
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com10 -> /dev/ttyS9
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com11 -> /dev/ttyS10
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com12 -> /dev/ttyS11
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com13 -> /dev/ttyS12
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com14 -> /dev/ttyS13
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com15 -> /dev/ttyS14
lrwxrwxrwx 1 wechat wechat 11 8月  22 07:51 com16 -> /dev/ttyS15
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com2 -> /dev/ttyS1
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com3 -> /dev/ttyS2
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com4 -> /dev/ttyS3
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com5 -> /dev/ttyS4
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com6 -> /dev/ttyS5
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com7 -> /dev/ttyS6
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com8 -> /dev/ttyS7
lrwxrwxrwx 1 wechat wechat 10 8月  22 07:51 com9 -> /dev/ttyS8
lrwxrwxrwx 1 wechat wechat  8 8月  22 07:51 d:: -> /dev/sdb
lrwxrwxrwx 1 wechat wechat 17 8月  22 07:51 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 wechat wechat  9 8月  22 07:51 e:: -> /dev/sdb1
lrwxrwxrwx 1 wechat wechat 12 8月  22 07:51 y: -> /home/wechat
lrwxrwxrwx 1 wechat wechat  1 8月  22 07:51 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/wechat/.deepinwine/Deepin-WeChat/drive_c/users/wechat/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2020年 08月 22日 星期六 07:51:46 UTC:kill WeChat.exe block
2020年 08月 22日 星期六 07:51:46 UTC:tag bottle: 
Traceback (most recent call last):
  File "/opt/deepinwine/tools/get_tray_window", line 28, in <module>
    get_tray_window()
  File "/opt/deepinwine/tools/get_tray_window", line 17, in get_tray_window
    bus = dbus.SessionBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 211, in __new__
    mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
2020年 08月 22日 星期六 07:51:46 UTC:active bottles: 
/home/wechat/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
[0822/075147:INFO:exception_record.cc(518)] [QB]Process ID: 58 Type: 1
[0822/075147:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x13e
  Serial number of failed request:  350
  Current serial number in output stream:  351
退出
启动 WeChat
Run Deepin-WeChat 2.6.8.65deepin0 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
total 0
lrwxrwxrwx 1 wechat wechat 10 8月  22 08:01 c: -> ../drive_c
lrwxrwxrwx 1 wechat wechat  8 8月  22 07:51 d:: -> /dev/sdb
lrwxrwxrwx 1 wechat wechat 17 8月  22 07:51 e: -> /media/wayne/Ntfs
lrwxrwxrwx 1 wechat wechat  9 8月  22 07:51 e:: -> /dev/sdb1
lrwxrwxrwx 1 wechat wechat 12 8月  22 08:01 y: -> /home/wechat
lrwxrwxrwx 1 wechat wechat  1 8月  22 08:01 z: -> /
CallApp Deepin-WeChat c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/wechat/.deepinwine/Deepin-WeChat/drive_c/users/wechat/Application Data/Tencent/WeChat/All Users/config/configEx.ini': 没有那个文件或目录
2020年 08月 22日 星期六 08:01:09 UTC:kill WeChat.exe block
2020年 08月 22日 星期六 08:01:09 UTC:No wine process found
/home/wechat/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
Starting process c:/Program Files/Tencent/WeChat/WeChat.exe ...
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
wine version: 2.18
[0822/080110:INFO:exception_record.cc(518)] [QB]Process ID: 8 Type: 1
[0822/080110:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x565
  Serial number of failed request:  1476
  Current serial number in output stream:  1477
退出

```

**Comment by slaughtering** [comment]
@zhz 6
